[package]
name = "lala-agent"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"

[dependencies]
axum = "0.8.8"
reqwest = { version = "0.13.1", default-features = false, features = ["native-tls", "http2"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
texting_robots = "0.2.2"
tokio = { version = "1.49.0", features = ["full"] }
tower = { version = "0.5.2", features = ["util"] }
url = "2.5.8"
